#!/bin/bash
#
# Build the upstream token-standard test harness DARs that dark-pool-test
# data-depends on.
#
# The harness (Splice.Testing.Registries.AmuletRegistry et al.) ships only as
# SOURCE in canton-network/splice's token-standard tree, targeting SDK 3.4.11 /
# LF 2.1, and its packages data-depend on `*-current.dar` artifacts (an SBT
# pipeline name the repo does not ship). We alias those names at the shipped,
# already-compiled versioned DARs under deps/splice-daml/dars/ (same
# package-ids the production dark-pool package uses) and build only the two
# source-only test packages.
#
# Idempotent (ln -sfn / mkdir -p / dpm build overwrite cleanly).
set -e
export LANG="${LANG:-C.UTF-8}"
export LC_ALL="${LC_ALL:-C.UTF-8}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
DARS="$ROOT/deps/splice-daml/dars"

# token-standard packages reference ../../daml/... ; we vendor daml/ as
# splice-daml/, so alias it.
ln -sfn splice-daml deps/daml

# Isolate the harness build from the repo-root multi-package.yaml: dpm searches
# upward for the nearest multi-package.yaml, and the root one lists the
# dark-pool packages (which may not exist yet, or which we do not want pulled
# into a harness build). A deps-local workspace stops that search at deps/.
cat > deps/multi-package.yaml <<'EOF'
# Harness-only multi-package workspace (generated by scripts/build-harness.sh).
# Stops dpm's upward multi-package.yaml search from reaching the repo root.
packages:
  - ./token-standard/examples/splice-token-test-dummy-holding
  - ./token-standard/examples/splice-token-test-trading-app
  - ./token-standard/splice-token-standard-test
EOF

# Pin the SDK the upstream test packages target.
dpm install 3.4.11

# Alias the *-current.dar data-deps at the shipped versioned DARs.
mkdir -p deps/splice-daml/splice-util/.daml/dist \
         deps/splice-daml/splice-amulet/.daml/dist
ln -sf "$DARS/splice-util-0.1.6.dar" \
       deps/splice-daml/splice-util/.daml/dist/splice-util-current.dar
ln -sf "$DARS/splice-amulet-0.1.19.dar" \
       deps/splice-daml/splice-amulet/.daml/dist/splice-amulet-current.dar

echo "==== building splice-token-test-trading-app ===="
( cd deps/token-standard/examples/splice-token-test-trading-app && dpm build )

# Alias the built trading-app DAR under the *-current.dar name that
# splice-token-standard-test's daml.yaml data-depends on.
mkdir -p deps/token-standard/examples/splice-token-test-trading-app/.daml/dist
ln -sf "$(ls -1 "$ROOT"/deps/token-standard/examples/splice-token-test-trading-app/.daml/dist/splice-token-test-trading-app-*.dar | grep -v current | sort -V | tail -1)" \
       deps/token-standard/examples/splice-token-test-trading-app/.daml/dist/splice-token-test-trading-app-current.dar

echo "==== building splice-token-standard-test ===="
( cd deps/token-standard/splice-token-standard-test && dpm build )

# Alias the built harness DAR under a stable *-current.dar name so dark-pool-test
# data-depends on a single fixed path; the version then lives only in upstream's
# daml.yaml and no consumer has to re-state it (it bumps with the splice tag).
HARNESS_DIST=deps/token-standard/splice-token-standard-test/.daml/dist
ln -sf "$(ls -1 "$ROOT"/$HARNESS_DIST/splice-token-standard-test-*.dar | grep -v current | sort -V | tail -1)" \
       "$HARNESS_DIST/splice-token-standard-test-current.dar"

echo ""
echo "Harness built:"
ls -1 "$HARNESS_DIST"/splice-token-standard-test-*.dar
